name = "SparseSpikes"
uuid = "7d3b8c41-e747-48b0-b081-32215591c5ce"
version = "0.1.1"
authors = ["Ladislas Walewski"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
ADTypes = "1.20.0"
DifferentiationInterface = "0.7.11"
FFTW = "1.9.0"
ForwardDiff = "1.3.0"
LineSearches = "7.4.0"
Mooncake = "0.4.174"
MosekTools = "0.15.10"
Polynomials = "4.1.0"
Printf = "1.11.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.9.0"

[extras]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[targets]
test = ["Revise"]
