name = "BLASSO"
uuid = "7d3b8c41-e747-48b0-b081-32215591c5ce"
authors = ["Ladislas Walewski <ladislas.colonna-walewski@warwick.ac.uk>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
FFTW = "7a1cc6ca-0e73-5c50-8b35-8df7ec6bd1ea"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Random = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MosekTools = "1ec41992-3fe8-5d83-bbdc-93deb6d179d5"
Polynomials = "f27b6e38-9f58-5fa6-bc11-3df91e5b3a1a"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[extras]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[targets]
test = ["Revise"]
